### ISSUE TITLE
Undefined is not an object (evaluating)  Proptypes.string

### ISSUE THREAD

**Issue by appongit** [UnPourTous/react-native-search-list#12]
I have just today install this and when i import it i got error

**Comment by erichua23** [comment]
what is your rn version ?

**Comment by appongit** [comment]
@erichua23 0.54.1 rn version

**Comment by erichua23** [comment]
It looks like your `prop-types` is not installed properly, try `npm i prop-types` under your project root and try again to confirm.

**Comment by appongit** [comment]
ok let me try, can i do like this with yarn
```
yarn add @unpourtous/react-native-search-list
yarn add prop-types
```

**Comment by appongit** [comment]
Thanks its working fine now
