### ISSUE TITLE
How can i implement search list with thumbnail

### ISSUE THREAD

**Issue by aliwaqassi** [UnPourTous/react-native-search-list#13]
![screen shot 2018-05-15 at 1 13 39 pm](https://user-images.githubusercontent.com/19648354/40045196-125d8b70-5843-11e8-9414-c39d338c71bb.png)
like this, is it possible?
need help

**Comment by erichua23** [comment]
Implement your own `renderRow`, like: 
``` js
  renderRow (item, sectionID, rowID, highlightRowFunc, isSearching) {
    // implement your own row component ....
    return <ContactListItem  />
  }
```

**Comment by aliwaqassi** [comment]
Thanks for your quick response, love you man
