### ISSUE TITLE
ios Cancel out of the screen

### ISSUE THREAD

**Issue by jsappme** [UnPourTous/react-native-search-list#6]
![image1 1](https://user-images.githubusercontent.com/13439477/34444185-e97f1efc-ec91-11e7-98c3-02efd66d2c0d.PNG)

Maybe we could remove the cancel if the search input is not selected. and only display the cancel button when it's needed.

**Comment by erichua23** [comment]
I've seen it in the newest rn version, I'll fix it, thx

**Comment by jpdenford** [comment]
I'm experiencing this issue too (iPhoneX simulator).
Otherwise great component thanks

**Comment by jpdenford** [comment]
This has been fixed at 40f3ff271ef1f6dd21966520d59bb7eb963a18ad  (just in case anyone is about to fork and fix it)

**Comment by jpdenford** [comment]
@erichua23 if you could publish to npm that'd be great. Thanks

**Comment by erichua23** [comment]
@jpdenford done, thx. 
sorry for the late, I failed to publish npm the last time because of some error, maybe network.
